set(BUILD_OS_OSX OFF)
set(BUILD_OS_LINUX OFF)
set(BUILD_OS_WINDOWS OFF)
if(NOT BUILD_OS_WIN32)
    set(BUILD_OS_WIN32 OFF)
endif()
if(NOT BUILD_OS_WIN64)
    set(BUILD_OS_WIN64 OFF)
endif()

if(APPLE)
    set(BUILD_OS_OSX ON)
elseif(WIN32)
    set(BUILD_OS_WINDOWS ON)
    if((NOT BUILD_OS_WIN32) AND (NOT BUILD_OS_WIN64))
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(BUILD_OS_WIN64 ON)
        else()
            set(BUILD_OS_WIN32 ON)
        endif()
    endif()
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(BUILD_OS_LINUX ON)
endif()
